Project
SirRedrick/faq-accordion-card pull request #1
Opened 2021-04-04 11:21 UTC by SirRedrick

2021-04-04 19:59 UTC, v1nn1k requested changes
Hi! Great one, don't forget to check out some other projects reviews ;)

2021-04-04 19:59 UTC, v1nn1k commented on src/components/Card.js
> +export default function Card({ title, children }) {
I'd add the PropTypes here

2021-04-04 19:59 UTC, v1nn1k commented on src/components/Card.js
> +				<img className={styles.mobile_image} src={mobileImage} alt="" />
Respect alt text)

2021-04-04 19:59 UTC, v1nn1k commented on src/components/FaqList.js
> +	const [opened, setOpened] = useState(null);
I think it's better to be explicit and say `openedIndex, setOpenedIndex`

2021-04-04 19:59 UTC, v1nn1k commented on src/components/FaqList.js
> +		if (opened === index) return setOpened(null);
use full block
```
if(something) {
  ...
}

2021-04-04 19:59 UTC, v1nn1k commented on src/components/FaqList.js
> +				<li key={index}>
Don't use array index as key

2021-04-04 19:59 UTC, v1nn1k commented on src/components/FaqList.js
> +				<li key={index}>
add local `const isOpened = opened === index` variable and use later on

2021-04-06 07:45 UTC, olehmell approved these changes
Good start. I have nothing to add after @v1nn1k! Good luck learning!

2021-04-09 15:29 UTC, kyrylo-burmelov commented on src/components/FaqList.js
> +					{opened === index ? <p>{entry.answer}</p> : null}
It's better to use && instead of ? in this case

2021-04-11 19:28 UTC, SirRedrick commented
Applied all of the suggestions listed in the reviews, would be really grateful if you could approve the changes

2021-04-11 20:01 UTC, v1nn1k commented
> Applied all of the suggestions listed in the reviews, would be really grateful if you could approve the changes

Great, I’ll try to take a look sometime later

2021-08-08 11:40 UTC, closed without merging